version: 3
services:
  mondodb:
    image: mongo
    restart: always
    container_name: mongodb-container
    port:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - /data/mongodb/data/db:/data/db
