version: "3.7"
services:
  perform-spring-mvc:
    image: perform-spring-mvc:latest
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "256M"
    ports:
      - "8080:8080"
  perform-spring-webflux:
    image: perform-spring-webflux:latest
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "256M"
    ports:
      - "8081:8081"