spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/distributed_redisson_lock?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: local
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.dialect.MySQL5Dialect
  data:
    redis:
      port: 6379
      host: localhost


